spring:
  application:
    name: forex-exchange
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    defer-datasource-initialization: true
    show-sql: true
  profiles:
    active:

server:
  port: 8020



